---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 8069966c03f70ea98a53771005c99d51dfb46db8
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: AnimalOrderService
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: org.mycompany
  name: animalorderservice
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: AnimalOrderService
    provider: fabric8
    group: org.mycompany
